export const MODAL_TYPE_TECH_ECONOMY_METRICS =
  "MODAL_TYPE_TECH_ECONOMY_METRICS";
export const MODAL_TYPE_FUTURE_METRICS = "MODAL_TYPE_FUTURE_METRICS";
export const MODAL_TYPE_ADD_PATTERN = "MODAL_TYPE_ADD_PATTERN";

// PatternBlock
export const MODAL_TYPE_PATTERN_SEARCH = "MODAL_TYPE_PATTERN_SEARCH";
export const MODAL_TYPE_PATTERN_SAVE = "MODAL_TYPE_PATTERN_SAVE";
export const MODAL_TYPE_PATTERN_LIST = "MODAL_TYPE_PATTERN_LIST";
export const MODAL_TYPE_TECH_GFH = "MODAL_TYPE_TECH_GFH";

// FilterBlock
// export const MODAL_TYPE_FILTER_DEVOBJECT = "MODAL_TYPE_FILTER_DEVOBJECT"
// export const MODAL_TYPE_FILTER_COUNTOBJECT = "MODAL_TYPE_FILTER_COUNTOBJECT"
// export const MODAL_TYPE_FILTER_LAYER = "MODAL_TYPE_FILTER_LAYER"

// SearchAreaBlock
export const MODAL_TYPE_RESULT_SAVE = "MODAL_TYPE_RESULT_SAVE";

// DashboardBlock
export const MODAL_TYPE_ADD_DASHBOARD = "MODAL_TYPE_ADD_DASHBOARD";

export const MODAL_TYPE_FILTER_VIEW = "MODAL_TYPE_FILTER_VIEW";
export const MODAL_TYPE_PATTERN_VIEW = "MODAL_TYPE_PATTERN_VIEW";
