export const BLOCK_TYPE_LIST_ITEMS = "BLOCK_TYPE_LIST_ITEMS";
export const BLOCK_TYPE_DESCRIPTION_VALUE = "BLOCK_TYPE_DESCRIPTION_VALUE";
export const LOADER_SEARCH_RESULTS = "LOADER_SEARCH_RESULTS";
